export const playerNames = {
  ARG: {
    2: "Emiliano Martínez",
    3: "Nahuel Molina",
    4: "Cristian Romero",
    5: "Nicolas Otamendi",
    6: "Nicolás Tagliafico",
    7: "Leonardo Balerdi",
    8: "Enzo Fernández",
    9: "Alexis Mac Allister",
    10: "Rodrigo De Paul",
    11: "Exequiel Palacios",
    12: "Leandro Paredes",
    14: "Nico Paz",
    15: "Franco Mastantuono",
    16: "Nicolás González",
    17: "Lionel Messi",
    18: "Lautaro Martínez",
    19: "Julián Álvarez",
    20: "Giuliano Simeone"
  },

MEX: {
  2: "Luis Malagón",
  3: "Johan Vásquez",
  4: "Jorge Sánchez",
  5: "César Montes",
  6: "Jesús Gallardo",
  7: "Israel Reyes",
  8: "Diego Lainez",
  9: "Carlos Rodríguez",
  10: "Edson Álvarez",
  11: "Orbelín Pineda",
  12: "Marcel Ruiz",
  14: "Érick Sánchez",
  15: "Hirving Lozano",
  16: "Santiago Giménez",
  17: "Raúl Jiménez",
  18: "Alexis Vega",
  19: "Roberto Alvarado",
  20: "César Huerta"
},
  RSA: {      
      2: "Ronwen Williams",
  3: "Sipho Chaine",
  4: "Aubrey Modiba",
  5: "Samukelo Kabini",
  6: "Mbekezeli Mbokazi",
  7: "Relebohile Mofokeng",
  8: "Themba Zwane",
  9: "Mihlali Mayambela",
  10: "Nkosinathi Sibisi",
  11: "Teboho Mokoena",
  12: "Thalente Mbatha",
  14: "Bathusi Aubaas",
  15: "Sibisi Sithole",
  16: "Sphephelo Mkhulise",
  17: "Lyle Foster",
  18: "Fawaaz Basadien",
  19: "Mduduzi Mdantsane",
  20: "Oswin Appollis"},

  KOR: {
  2: "Hyeonwoo Jo",
  3: "Seunggyu Kim",
  4: "Minjae Kim",
  5: "Yumin Cho",
  6: "Youngwoo Seol",
  7: "Jungho Lee",
  8: "Taehsok Lee",
  9: "Munjun Lee",
  10: "Jaejung Lee",
  11: "Heechan Hwang",
  12: "Kangin Lee",
  14: "Seungho Paik",
  15: "Jens Castrop",
  16: "Gyeong Lee",
  17: "Uisung Cho",
  18: "Heungmin Son",
  19: "Heechan Hwang",
  20: "Hyeongyu Oh"
},
  CZE: {
  2: "Matěj Kovář",
  3: "Jindřich Staněk",
  4: "Ladislav Krejčí",
  5: "Vladimír Coufal",
  6: "Jaroslav Zelený",
  7: "Tomáš Holeš",
  8: "David Zima",
  9: "Michal Sadílek",
  10: "Lukáš Provod",
  11: "Lukáš Červ",
  12: "Tomáš Souček",
  14: "Pavel Šulc",
  15: "Matěj Vydra",
  16: "Václav Černý",
  17: "Tomáš Chorý",
  18: "Vladimír Černý",
  19: "Adam Hložek",
  20: "Patrik Schick"
},
  CAN: {
  2: "Dayne St. Clair",
  2: "Alphonso Davies",
  4: "Alistair Johnston",
  5: "Samuel Adekugbe",
  6: "Richie Laryea",
  14: "Jacob Shaffelburg",
  7: "Derek Cornelius",
  8: "Moïse Bombito",
  9: "Kamal Miller",
  10: "Stephen Eustáquio",
  11: "Ismaël Koné",
  12: "Jonathan Osorio",
  15: "Mathieu Choinière",
  16: "Niko Sigur",
  17: "Tajon Buchanan",
  18: "Liam Millar",
  19: "Cyle Larin",
  20: "Jonathan David"
},
  BIH: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  QAT: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  SUI: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  BRA: {
  2: "Alisson",
  3: "Bento",
  4: "Marquinhos",
  5: "Éder Militão",
  6: "Gabriel Magalhães",
  7: "Danilo",
  8: "Wesley",
  9: "Lucas Paquetá",
  10: "Casemiro",
  11: "Bruno Guimarães",
  12: "Luiz Henrique",
  14: "Vinícius Júnior",
  15: "Rodrygo",
  16: "João Pedro",
  17: "Matheus Cunha",
  18: "Gabriel Martinelli",
  19: "Raphinha",
  20: "Estêvão"
},
  MAR: {
  2: "Yassine Bounou",
  3: "Munir El Kajoui",
  4: "Achraf Hakimi",
  5: "Noussair Mazraoui",
  6: "Nayef Aguerd",
  7: "Romain Saïss",
  8: "Jawad El Yamiq",
  9: "Adam Masina",
  10: "Sofyan Amrabat",
  11: "Azzedine Ounahi",
  12: "Bilal El Khannouss",
  14: "Ismael Saibari",
  15: "Youssef En-Nesyri",
  16: "Abde Ezzalzouli",
  17: "Soufiane Rahimi",
  18: "Brahim Díaz",
  19: "Ayoub El Kaabi"
},
  HAI: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  SCO: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  USA: {
  2: "Matt Freese",
  3: "Chris Richards",
  4: "Tim Ream",
  5: "Mark McKenzie",
  6: "Mark McKenzie",
  7: "Antonee Robinson",
  8: "Tyler Adams",
  9: "Tanner Tessmann",
  10: "Weston McKennie",
  11: "Cristian Roldan",
  12: "Timothy Weah",
  14: "Diego Luna",
  15: "Malik Tillman",
  16: "Christian Pulisic",
  17: "Brenden Aaronson",
  18: "Ricardo Pepi",
  19: "Haji Wright",
  20: "Folarin Balogun"
},
  PAR: {
  2: "Roberto Fernández",
  3: "Orlando Gill",
  4: "Gustavo Gómez",
  5: "Fabián Balbuena",
  6: "Juan José Cáceres",
  7: "Omar Alderete",
  8: "Junior Alonso",
  9: "Matías Villasanti",
  10: "Diego Gómez",
  11: "Damián Bobadilla",
  12: "Andrés Cubas",
  13: "Matías Galarza Fonda",
  14: "Julio Enciso",
  15: "Alejandro Romero Gamarra",
  16: "Miguel Almirón",
  18: "Ramón Sosa",
  19: "Ángel Romero",
  20: "Antonio Sanabria"
},
  AUS: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  TUR: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  GER: {
  2: "Marc-André ter Stegen",
  3: "Jonathan Tah",
  4: "David Raum",
  5: "Nico Schlotterbeck",
  6: "Antonio Rüdiger",
  7: "Waldemar Anton",
  8: "Yann Bisseck",
  9: "Maximilian Mittelstädt",
  10: "Joshua Kimmich",
  11: "Florian Wirtz",
  12: "Felix Nmecha",
  14: "Leon Goretzka",
  15: "Jamal Musiala",
  16: "Serge Gnabry",
  17: "Kai Havertz",
  18: "Leroy Sané",
  19: "Karim Adeyemi",
  20: "Nick Woltemade"
},
  CUW: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  CIV: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  ECU: {
  2: "Hernán Galíndez",
  3: "Gonzalo Valle",
  4: "Piero Hincapié",
  5: "Pervis Estupiñán",
  6: "Willian Pacho",
  7: "Ángelo Preciado",
  8: "Joel Ordóñez",
  9: "Moisés Caicedo",
  10: "Alan Franco",
  11: "Kendry Páez",
  12: "Pedro Vite",
  14: "Jhon Yeboah",
  15: "Leonardo Campana",
  16: "Gonzalo Plata",
  17: "Nilson Angulo",
  18: "Alan Minda",
  19: "Kevin Rodríguez",
  20: "Enner Valencia"
},
  NED: {
  2: "Bart Verbruggen",
  3: "Virgil van Dijk",
  4: "Micky van de Ven",
  5: "Jurriën Timber",
  6: "Denzel Dumfries",
  7: "Nathan Aké",
  8: "Jeremie Frimpong",
  9: "Jan Paul van Hecke",
  10: "Tijjani Reijnders",
  11: "Ryan Gravenberch",
  12: "Teun Koopmeiners",
  14: "Frenkie de Jong",
  15: "Xavi Simons",
  16: "Justin Kluivert",
  17: "Memphis Depay",
  18: "Donyell Malen",
  19: "Wout Weghorst",
  20: "Cody Gakpo"
},
  JPN: {
  2: "Zion Suzuki",
  3: "Henry Heroki Mochizuki",
  4: "Ayumu Seko",
  5: "Junnosuke Suzuki",
  6: "Shogo Taniguchi",
  7: "Tsuyoshi Watanabe",
  8: "Koki Sano",
  9: "Yuki Soma",
  10: "Ao Tanaka",
  11: "Daichi Kamada",
  12: "Takefusa Kubo",
  14: "Ritsu Doan",
  15: "Keito Nakamura",
  16: "Takumi Minamino",
  17: "Shuto Machino",
  18: "Junya Ito",
  19: "Kei Ogawa",
  20: "Ayase Ueda"
},
  SWE: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  TUN: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  BEL: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  EGY: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  IRN: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  NZL: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  ESP: {
  2: "Unai Simón",
  3: "Robin Le Normand",
  4: "Aymeric Laporte",
  5: "Dean Huijsen",
  6: "Pedro Porro",
  7: "Dani Carvajal",
  8: "Marc Cucurella",
  9: "Martín Zubimendi",
  10: "Rodri",
  11: "Pedri",
  12: "Fabián Ruiz",
  14: "Mikel Merino",
  15: "Lamine Yamal",
  16: "Dani Olmo",
  17: "Nico Williams",
  18: "Ferran Torres",
  19: "Álvaro Morata",
  20: "Mikel Oyarzabal"
},
  CPV: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  KSA: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  URU: {
  3: "Santiago Mele",
  2: "Sergio Rochet",
  4: "Ronald Araújo",
  5: "José María Giménez",
  6: "Sebastián Cáceres",
  7: "Mathías Olivera",
  8: "Guillermo Varela",
  9: "Nahitan Nández",
  10: "Federico Valverde",
  11: "Giorgian De Arrascaeta",
  12: "Rodrigo Bentancur",
  14: "Manuel Ugarte",
  15: "Nicolás De La Cruz",
  16: "Maxi Araújo",
  17: "Darwin Núñez",
  18: "Federico Viñas",
  19: "Rodrigo Aguirre",
  20: "Facundo Pellistri"
},
  FRA: {
  2: "Mike Maignan",
  3: "Théo Hernández",
  4: "William Saliba",
  5: "Jules Koundé",
  6: "Ibrahima Konaté",
  7: "Dayot Upamecano",
  8: "Lucas Digne",
  9: "Aurélien Tchouaméni",
  10: "Eduardo Camavinga",
  11: "Manu Koné",
  12: "Adrien Rabiot",
  14: "Michael Olise",
  15: "Ousmane Dembélé",
  16: "Bradley Barcola",
  17: "Désiré Doué",
  18: "Kingsley Coman",
  19: "Hugo Ekitiké",
  20: "Kylian Mbappé"
},
  SEN: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  IRQ: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  NOR: {    2: "Jugador 2",
    3: "Jugador 3",
    4: "Jugador 4",
    5: "Jugador 5",
    6: "Jugador 6",
    7: "Jugador 7",
    8: "Jugador 8",
    9: "Jugador 9",
    10: "Jugador 10",
    11: "Jugador 11",
    12: "Jugador 12",
    14: "Jugador 14",
    15: "Jugador 15",
    16: "Jugador 16",
    17: "Jugador 17",
    18: "Jugador 18",
    19: "Jugador 19",
    20: "Jugador 20"},
  ALG: {
  2: "Alexis Guendouz",
  3: "Ramy Bensebaini",
  4: "Youcef Atal",
  5: "Rayan Aït-Nouri",
  6: "Mohamed Amine Tougaï",
  7: "Aïssa Mandi",
  8: "Ismaël Bennacer",
  9: "Houssem Aouar",
  10: "Hicham Boudaoui",
  11: "Ramiz Zerrouki",
  12: "Nabil Bentaleb",
  14: "Farès Chaïbi",
  15: "Riyad Mahrez",
  16: "Saïd Benrahma",
  17: "Anis Hadj Moussa",
  18: "Amine Gouiri",
  19: "Baghdad Bounedjah",
  20: "Mohamed Amoura"
},
  AUT: {
  2: "Alexander Schlager",
  3: "Patrick Pentz",
  4: "David Alaba",
  5: "Kevin Danso",
  6: "Philipp Lienhart",
  7: "Stefan Posch",
  8: "Phillipp Mwene",
  9: "Alexander Prass",
  10: "Xaver Schlager",
  11: "Marcel Sabitzer",
  12: "Konrad Laimer",
  14: "Florian Grillitsch",
  15: "Nicolas Seiwald",
  16: "Romano Schmid",
  17: "Patrick Wimmer",
  18: "Christoph Baumgartner",
  19: "Michael Gregoritsch",
  20: "Marko Arnautović"
},
  JOR: {
  2: "Yazeed Abulaila",
  3: "Ihsan Haddad",
  4: "Mohammad Abu Hasheesh",
  5: "Yazan Al-Arab",
  6: "Abdallah Nasib",
  7: "Salem Obaid",
  8: "Mohannad Abu Taha",
  9: "Ibrahim Saadeh",
  10: "Nizar Al-Rashdan",
  11: "Noor Al-Rawabdeh",
  12: "Mohammad Abu Zraiq",
  14: "Amer Jamous",
  15: "Mousa Al-Taamari",
  16: "Yazan Al-Naimat",
  17: "Mahmoud Al-Mardi",
  18: "Ali Olwan",
  19: "Mohammad Abu Zrayq",
  20: "Yousef Abou Jalboush"
},
  POR: {
  2: "Diogo Costa",
  3: "José Sá",
  4: "Rúben Dias",
  5: "João Cancelo",
  6: "Diogo Dalot",
  7: "Nuno Mendes",
  8: "Gonçalo Inácio",
  9: "Bernardo Silva",
  10: "Bruno Fernandes",
  11: "Rúben Neves",
  12: "Vitinha",
  14: "João Neves",
  15: "Cristiano Ronaldo",
  16: "Francisco Trincão",
  17: "João Félix",
  18: "Gonçalo Ramos",
  19: "Pedro Neto",
  20: "Rafael Leão"
},
  COD: {
  2: "Lionel Mpasi",
  3: "Aaron Wan-Bissaka",
  4: "Axel Tuanzebe",
  5: "Arthur Masuaku",
  6: "Chancel Mbemba",
  7: "Joris Kayembe",
  8: "Charles Pickel",
  9: "Ngal'ayel Mukau",
  10: "Edo Kayembe",
  11: "Samuel Moutoussamy",
  12: "Noé Dussenne",
  14: "Théo Bongonda",
  15: "Meschack Elia",
  16: "Yoane Wissa",
  17: "Edo Kayembe",
  18: "Fiston Mayele",
  19: "Cédric Bakambu",
  20: "Nathanaël Mbuku"
},
  UZB: {
2: "Utkir Yusupov",
3: "Farrukh Sayfiev",
4: "Sherzod Nasrullaev",
5: "Umar Eshmurodov",
6: "Husniddin Aliqulov",
7: "Rustam Ashurmatov",
8: "Khojiakbar Alijonov",
9: "Abdukodir Khusanov",
10: "Odiljon Hamrobekov",
11: "Otabek Shukurov",
12: "Jamshid Iskanderov",
14: "Azizbek Turgunboev",
15: "Khojimat Erkinov",
16: "Eldor Shomurodov",
17: "Oston Urunov",
18: "Jaloliddin Masharipov",
19: "Igor Sergeev",
20: "Abbosbek Fayzullaev"
},
  COL: {
2: "Camilo Vargas",
3: "David Ospina",
4: "Davinson Sánchez",
5: "Yerry Mina",
6: "Daniel Muñoz",
7: "Johan Mojica",
8: "Jhon Lucumí",
9: "Santiago Arias",
10: "Jefferson Lerma",
11: "Kevin Castaño",
12: "Richard Ríos",
14: "James Rodríguez",
15: "Juan Fernando Quintero",
16: "Jorge Carrascal",
17: "Jhon Arias",
18: "Jhon Córdoba",
19: "Luis Suárez",
20: "Luis Díaz"
},
  ENG: {
2: "Jordan Pickford",
3: "John Stones",
4: "Marc Guéhi",
5: "Ezri Konsa",
6: "Trent Alexander-Arnold",
7: "Reece James",
8: "Dan Burn",
9: "Jordan Henderson",
10: "Declan Rice",
11: "Jude Bellingham",
12: "Cole Palmer",
14: "Morgan Rogers",
15: "Anthony Gordon",
16: "Phil Foden",
17: "Bukayo Saka",
18: "Harry Kane",
19: "Marcus Rashford",
20: "Ollie Watkins"
},
  CRO: {
2: "Dominik Livaković",
3: "Duje Ćaleta-Car",
4: "Joško Gvardiol",
5: "Josip Stanišić",
6: "Luka Vušković",
7: "Josip Šutalo",
8: "Kristijan Jakić",
9: "Luka Modrić",
10: "Mateo Kovačić",
11: "Martin Baturina",
12: "Lovro Majer",
14: "Mario Pašalić",
15: "Petar Sučić",
16: "Ivan Perišić",
17: "Marco Pašalić",
18: "Ante Budimir",
19: "Andrej Kramarić",
20: "Franjo Ivanović"
},
  GHA: {
2: "Lawrence Ati Zigi",
3: "Tariq Lamptey",
4: "Mohammed Salisu",
5: "Alidu Seidu",
6: "Alexander Djiku",
7: "Gideon Mensah",
8: "Caleb Ekuban",
9: "Abdul Issahaku Fatawu",
10: "Thomas Partey",
11: "Salis Abdul Samed",
12: "Kamaldeen Sulemana",
14: "Mohammed Kudus",
15: "Iñaki Williams",
16: "Jordan Ayew",
17: "André Ayew",
18: "Joseph Paintsil",
19: "Osman Bukari",
20: "Antoine Semenyo"
},
  PAN: {
2: "Orlando Mosquera",
3: "Luis Mejía",
4: "Fidel Escobar",
5: "Andrés Andrade",
6: "Michael Amir Murillo",
7: "Eric Davis",
8: "José Córdoba",
9: "César Blackman",
10: "Cristian Martínez",
11: "Aníbal Godoy",
12: "Adalberto Carrasquilla",
14: "Edgar Bárcenas",
15: "Carlos Harvey",
16: "Ismael Díaz",
17: "José Fajardo",
18: "Cecilio Waterman",
19: "José Luis Rodríguez",
20: "Alberto Quintero"
},

  CC: {
    1: "Lamine Yamal",
    2: "Joshua Kimmich",
    3: "Harry Kane",
    4: "Santiago Gimenez",
    5: "Josko Gvardiol",
    6: "Federico Valverde",
    7: "Jefferson Lerma",
    8: "Enner Valencia",
    9: "Gabriel Magalhaes",
    10: "Virgil van Dijk",
    11: "Alphonso Davies",
    12: "Emiliano Martinez",
    13: "Raul Jimenez",
    14: "Lautaro Martinez"
  }
}