export const updateNames = {
  MEX2: 'Guillermo Ochoa',
  MEX8: 'Gilberto Mora',
  MEX9: 'Álvaro Fidalgo',
  MEX12: 'Érik Lira',
  MEX14: 'Brian Gutiérrez',
  MEX15: 'Armando González',
  RSA8: 'Ime Okon',
  RSA14: 'Themba Zwane',
  RSA16: 'Jayden Adams',
  RSA19: 'Relebohile Mofokeng',
  KOR5: 'Moonhwan Kim',
  KOR9: 'Taehyeon Kim',
  CZE15: 'David Douděra',
  CZE16: 'Vladimír Darida',
  CZE18: 'Mojmír Chytil',
  CAN5: 'Joel Waterman',
  CAN9: 'Alfie Jones',
  QAT8: 'Ayoub Aloui',
  QAT14: 'Jassem Gaber',
  QAT19: 'Mohammed Muntari',
  BRA3: 'Weverton',
  BRA5: 'Alex Sandro',
  BRA15: 'Neymar Jr.',
  BRA16: 'Endrick',
  BRA20: 'Igor Thiago',
  MAR7: 'Issa Diop',
  MAR8: 'Anass Salah-Eddine',
  MAR9: 'Chadi Riad',
  MAR12: 'Neil El Aynaoui',
  MAR16: 'Chemsdine Talbi',
  HAI8: 'Wilguens Paugain',
  HAI14: 'Wilson Isidor',
  SCO12: 'Nathan Patterson',
  USA9: 'Gio Reyna',
  USA14: 'Sebastian Berhalter',
  PAR9: 'Braian Ojeda',
  PAR19: 'Álex Arce',
  AUS3: 'Paul Izzo',
  AUS9: 'Jason Geria',
  AUS12: 'Ajdin Hrustic',
  AUS16: 'Paul Okon-Engstler',
  AUS17: 'Nishan Velupillay',
  GER2: 'Manuel Neuer',
  GER8: 'Malick Thiaw',
  GER9: 'Angelo Stiller',
  GER16: 'Aleksandar Pavlović',
  GER19: 'Deniz Undav',
  CIV7: 'Guéla Doué',
  CIV14: 'Nicolas Pépé',
  CIV16: 'Elye Wahi',
  ECU15: 'Anthony Valencia',
  NED8: 'Quinten Timber',
  NED15: 'Noa Lang',
  JPN3: 'Hiroki Ito',
  JPN9: 'Wataru Endo',
  JPN16: 'Daizen Maeda',
  JPN17: 'Yuito Suzuki',
  SWE5: 'Carl Starfelt',
  SWE9: 'Besfort Zeneli',
  SWE16: 'Benjamin Nygren',
  SWE17: 'Alexander Bernhardsson',
  TUN2: 'Abdelmouhib Chamakh',
  TUN6: 'Omar Rekik',
  TUN10: 'Rani Khedira',
  TUN11: 'Anis Ben Slimane',
  TUN12: 'Mohamed Belhadj Mahmoud',
  TUN19: 'Sebastian Tounekti',
  TUN20: 'Mortadha Ben Ouanes',
  BEL19: 'Dodi Lukébakio',
  EGY4: 'Mohamed Abdelmonem',
  EGY6: 'Mahmoud Saber',
  EGY16: 'Ibrahim Adel',
  EGY18: 'Haissem Hassan',
  IRN3: 'Arya Yousefi',
  IRN9: 'Ali Nemati',
  IRN14: 'Amirmohammad Razzaghinia',
  IRN17: 'Ali Alipour',
  IRN20: 'Amirhossein Hosseinzadeh',
  ESP3: 'Pau Cubarsí',
  ESP5: 'Alejandro Grimaldo',
  ESP7: 'Marcos Llorente',
  ESP19: 'Yeremy Pino',
  CPV11: 'Laros Duarte',
  CPV20: 'Nuno Da Costa',
  KSA3: 'Abdulelah Alamri',
  KSA14: 'Mohamed Kanno',
  KSA15: 'Ali Majrashi',
  KSA17: 'Sultan Mandash',
  URU9: 'Matías Viña',
  FRA10: 'N’Golo Kanté',
  FRA18: 'Rayan Cherki',
  FRA19: 'Marcus Thuram',
  SEN17: 'Ibrahim Mbaye',
  IRQ17: 'Kevin Yakob',
  NOR17: 'Jens Petter Hauge',
  ARG15: 'Giovani Lo Celso',
  ALG2: 'Luca Zidane',
  ALG4: 'Rafik Belghali',
  ALG8: 'Ibrahim Maza',
  ALG16: 'Adil Boulbina',
  ALG19: 'Farès Ghedjemis',
  JOR16: 'Odeh Fakhoury',
  UZB6: 'Jakhongir Urozov',
  UZB14: 'Azizjon Ganiev',
  UZB15: 'Akmal Mozgovoy',
  ENG6: 'Nico O’Reilly',
  ENG12: 'Eberechi Eze',
  ENG16: 'Noni Madueke',
  CRO12: 'Nikola Vlašić',
  CRO20: 'Igor Matanović',
  GHA3: 'Benjamin Asare',
  GHA4: 'Kojo Peprah Oppong',
  GHA6: 'Jonas Adjetey',
  GHA11: 'Kwasi Sibo',
  GHA14: 'Christopher Bonsu Baah',
  GHA17: 'Ernest Nuamah',
  GHA18: 'Brandon Thomas-Asante',
  GHA19: 'Prince Adu',
};

// Códigos de las Updates que Facu ya pegó físicamente. Se completa manualmente.
export const updatesApplied = [];
